In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# UEFA club European Cup Web Scraping

In this notebook, we will develop and review a web scraper to extract all matches played in the major European Club Cup tournments from 1980 onward. The goal is to create a dataset with the following information:

- `season`
- `competition`
- `round`
- `team_a`,
- `country_a`,
- `team_b`,
- `country_b`
- `score_leg1`
- `score_leg2`
- `score_aggregate`
- `extra_time`
- `penalties`

The first step of our analysis will concentrate on single results only, meaning that we will use the information stored in the first nine columns only. The idea, at least as a first insight, is to compare the winning/points ratio of all clubs by nation without giving any weight to the competition, something that can be done in a further step. 

The process to build the webscraper is iterative and is done in collaboration with Claude. The web resources that will be used as main source is well structured and yet contains different spots where the script to scrape the data must be adapted as we collect the data - *learning point*.

## Scraping data from kassiesa.net

- source: [kassiesa.net](https://kassiesa.net/uefa/index.html)

This database contains all match results and calculated coefficients of European Cup football since 1955, covering all rounds including qualifiers. It's one of the most thorough free sources and is well-regarded among football statisticians. It will be used as starting point for collecting the data. A possible exhaustive approach might be:

- Starting with Kassiesa.net as ground truth (it has all three competitions, nationalities, and correct results). Scrapeing the season-by-season match pages (they're structured HTML tables). This will give us ~1980–present across all competitions.
- Supplement with jalapic/champs CSV (free direct download) for Champions League 1980–2017 as a cross-check.
- For the extra-time / penalties distinction, ***Kassiesa.net does not always separate these from 90-min scores***. We may need to cross-reference with EuroCupsHistory (eurocupshistory.com) for knockout rounds specifically.

In [ ]:
import subprocess
import sys

# uncomment to run the test

# # Run the uefa_scraper.py script with default arguments
# result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '1981', '--end', '1983', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# # Print the output
# print("STDOUT:")
# print(result.stdout)
# print("STDERR:")
# print(result.stderr)

#### Testing the scripts through the '80

In [3]:
# uncomment to run the test

# # Run the uefa_scraper.py script with default arguments
# result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '1980', '--end', '1990', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# # Print the output
# print("STDOUT:")
# print(result.stdout)
# print("STDERR:")
# print(result.stderr)

#### Testing the scripts through the '90

In [4]:
# uncomment to run the test

# # Run the uefa_scraper.py script with default arguments
# result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '1990', '--end', '2000', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# # Print the output
# print("STDOUT:")
# print(result.stdout)
# print("STDERR:")
# print(result.stderr)

#### Testing the scripts from 2000 to 2010

In [5]:
# uncomment to run the test

# # Run the uefa_scraper.py script with default arguments
# result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '2000', '--end', '2010', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# # Print the output
# print("STDOUT:")
# print(result.stdout)
# print("STDERR:")
# print(result.stderr)

#### Testing the script from 2010 to 2020

In [6]:
# # uncomment to run the test

# # Run the uefa_scraper.py script with default arguments
# result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '2010', '--end', '2020', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# # Print the output
# print("STDOUT:")
# print(result.stdout)
# print("STDERR:")
# print(result.stderr)

#### Testing the script 2020 to 2025

In [7]:
# # uncomment to run the test

# # Run the uefa_scraper.py script with default arguments
# result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '2020', '--end', '2026', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# # Print the output
# print("STDOUT:")
# print(result.stdout)
# print("STDERR:")
# print(result.stderr)

#### Testing the script 1979 to 2026

In [3]:
import subprocess
import sys

# Run the uefa_scraper.py script with default arguments
result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '1976', '--end', '2026', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# Print the output
print("STDOUT:")
print(result.stdout)
print("STDERR:")
print(result.stderr)

STDOUT:
Scraping 51 seasons (1975/76 → 2025/26) …

  1975/76 … 125 matches
  1976/77 … 126 matches
  1977/78 … 125 matches
  1978/79 … 125 matches
  1979/80 … 127 matches
  1980/81 … 128 matches
  1981/82 … 127 matches
  1982/83 … 127 matches
  1983/84 … 125 matches
  1984/85 … 125 matches
  1985/86 … 123 matches
  1986/87 … 123 matches
  1987/88 … 126 matches
  1988/89 … 125 matches
  1989/90 … 127 matches
  1990/91 … 125 matches
  1991/92 … 133 matches
  1992/93 … 139 matches
  1993/94 … 154 matches
  1994/95 … 172 matches
  1995/96 … 181 matches
  1996/97 … 203 matches
  1997/98 … 221 matches
  1998/99 … 226 matches
  1999/00 … 259 matches
  2000/01 … 263 matches
  2001/02 … 263 matches
  2002/03 … 263 matches
  2003/04 … 247 matches
  2004/05 … 311 matches
  2005/06 … 312 matches
  2006/07 … 321 matches
  2007/08 … 327 matches
  2008/09 … 327 matches
  2009/10 … 346 matches
  2010/11 … 348 matches
  2011/12 … 348 matches
  2012/13 … 347 matches
  2013/14 … 347 matches
  2014/15 … 350 matches
  2015/16 … 347 matches
  2016/17 … 344 matches
  2017/18 … 347 matches
  2018/19 … 370 matches
  2019/20 … 370 matches
  2020/21 … 370 matches
  2021/22 … 411 matches
  2022/23 … 405 matches
  2023/24 … 406 matches
  2024/25 … 678 matches
  2025/26 … 659 matches

Total: 13124 matches
Writing → ../data/uefa_results.csv
Done ✓

STDERR:

output:
```
STDOUT:
Scraping 48 seasons (1978/79 → 2025/26) …
  1975/76 … 125 matches
  1976/77 … 126 matches
  1977/78 … 125 matches
  1978/79 … 125 matches
  1979/80 … 127 matches
  1980/81 … 128 matches
  1981/82 … 127 matches
  1982/83 … 127 matches
  1983/84 … 125 matches
  1984/85 … 125 matches
  1985/86 … 123 matches
  1986/87 … 123 matches
  1987/88 … 126 matches
  1988/89 … 125 matches
  1989/90 … 127 matches
  1990/91 … 125 matches
  1991/92 … 133 matches
  1992/93 … 139 matches
  1993/94 … 154 matches
  1994/95 … 172 matches
  1995/96 … 181 matches
  1996/97 … 203 matches
  1997/98 … 221 matches
  1998/99 … 226 matches
  1999/00 … 259 matches
  2000/01 … 263 matches
  2001/02 … 263 matches
  2002/03 … 263 matches
  2003/04 … 247 matches
  2004/05 … 311 matches
  2005/06 … 312 matches
  2006/07 … 321 matches
  2007/08 … 327 matches
  2008/09 … 327 matches
  2009/10 … 346 matches
  2010/11 … 348 matches
  2011/12 … 348 matches
  2012/13 … 347 matches
  2013/14 … 347 matches
  2014/15 … 350 matches
  2015/16 … 347 matches
  2016/17 … 344 matches
  2017/18 … 347 matches
  2018/19 … 370 matches
  2019/20 … 370 matches
  2020/21 … 370 matches
  2021/22 … 411 matches
  2022/23 … 405 matches
  2023/24 … 406 matches
  2024/25 … 678 matches
  2025/26 … 659 matches

Total: 13124 matches
Writing → ../data/uefa_results.csv
Done ✓

STDERR:
```

In [4]:
raw_data = pd.read_csv('../data/uefa_results.csv')
raw_data.head()

,season,competition,round,team_a,country_a,team_b,country_b,score_leg1,score_leg2,score_aggregate,extra_time,penalties
0,1975/76,CL,Round 1,Benfica,Por,Fenerbahçe,Tur,7-0,0-1,7-1,no,no
1,1975/76,CL,Round 1,Borussia Mönchengladbach,Ger,Wacker Innsbruck,Aut,1-1,6-1,7-2,no,no
2,1975/76,CL,Round 1,KB København,Den,AS Saint-Étienne,Fra,0-2,1-3,1-5,no,no
3,1975/76,CL,Round 1,CSKA Sofia,Bul,Juventus,Ita,2-1,0-2,2-3,no,no
4,1975/76,CL,Round 1,Floriana,Mlt,Hajduk Split,YUG,0-5,0-3,0-8,no,no

In [6]:
raw_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13124 entries, 0 to 13123
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   season           13124 non-null  str
 1   competition      13124 non-null  str
 2   round            13124 non-null  str
 3   team_a           13124 non-null  str
 4   country_a        13124 non-null  str
 5   team_b           13124 non-null  str
 6   country_b        13124 non-null  str
 7   score_leg1       13124 non-null  str
 8   score_leg2       11569 non-null  str
 9   score_aggregate  13124 non-null  str
 10  extra_time       13124 non-null  str
 11  penalties        13124 non-null  str
dtypes: str(12)
memory usage: 1.2 MB

In [7]:
raw_data.head()

,season,competition,round,team_a,country_a,team_b,country_b,score_leg1,score_leg2,score_aggregate,extra_time,penalties
0,1975/76,CL,Round 1,Benfica,Por,Fenerbahçe,Tur,7-0,0-1,7-1,no,no
1,1975/76,CL,Round 1,Borussia Mönchengladbach,Ger,Wacker Innsbruck,Aut,1-1,6-1,7-2,no,no
2,1975/76,CL,Round 1,KB København,Den,AS Saint-Étienne,Fra,0-2,1-3,1-5,no,no
3,1975/76,CL,Round 1,CSKA Sofia,Bul,Juventus,Ita,2-1,0-2,2-3,no,no
4,1975/76,CL,Round 1,Floriana,Mlt,Hajduk Split,YUG,0-5,0-3,0-8,no,no

In [8]:
raw_data[raw_data['round'] ==  'Final'][:10]

,season,competition,round,team_a,country_a,team_b,country_b,score_leg1,score_leg2,score_aggregate,extra_time,penalties
30,1975/76,CL,Final,Bayern München,Ger,AS Saint-Étienne,Fra,1-0,NaN,1-0,no,no
61,1975/76,CW,Final,Anderlecht,Bel,West Ham United,Eng,4-2,NaN,4-2,no,no
124,1975/76,EL,Final,Liverpool,Eng,Club Brugge,Bel,3-2,1-1,4-3,no,no
155,1976/77,CL,Final,Liverpool,Eng,Borussia Mönchengladbach,Ger,3-1,NaN,3-1,no,no
187,1976/77,CW,Final,Hamburger SV,Ger,Anderlecht,Bel,2-0,NaN,2-0,no,no
250,1976/77,EL,Final,Juventus,Ita,Athletic Bilbao,Esp,1-0,1-2,2-2,no,no
280,1977/78,CL,Final,Liverpool,Eng,Club Brugge,Bel,1-0,NaN,1-0,no,no
312,1977/78,CW,Final,Anderlecht,Bel,Austria Wien,Aut,4-0,NaN,4-0,no,no
375,1977/78,EL,Final,SC Bastia,Fra,PSV Eindhoven,Ned,0-0,0-3,0-3,no,no
407,1978/79,CL,Final,Nottingham Forest,Eng,Malmö FF,Swe,1-0,NaN,1-0,no,no

The scraper addresses properly the fact that some finals were played within a single match.

## Sample checking

The dataset contains 12747 entries and checking all of them would be an extensive taks. One feasible strategy is to sample $n$ entries and double veryfing the reported information. The size of the sample may depend on the size of the dataset and the cost to verify the information (the cost involve the time and resources you need to verify).

In [10]:
raw_data.sample(20, random_state=1).sort_values('season', ascending = False)

,season,competition,round,team_a,country_a,team_b,country_b,score_leg1,score_leg2,score_aggregate,extra_time,penalties
12834,2025/26,EL,League Stage,OGC Nice,Fra,Go Ahead Eagles,Ned,3-1,NaN,3-1,no,no
12879,2025/26,CO,1st Qualifying Round,Urartu FC,Arm,Neman Grodno,Bls,1-2,0-4,1-6,no,no
12428,2024/25,CO,League Stage,Djurgårdens IF,Swe,Legia Warsaw,Pol,3-1,NaN,3-1,no,no
12209,2024/25,CO,1st Qualifying Round,Torpedo Kutaisi,Geo,KF Tirana,Alb,1-1,1-0,2-1,no,no
9553,2018/19,CL,Round 2,Tottenham Hotspur,Eng,Borussia Dortmund,Ger,3-0,1-0,4-0,no,no
9333,2017/18,EL,Qualifying Play-off Round,Club Brugge,Bel,AEK Athens,Gre,0-0,0-3,0-3,no,no
8276,2014/15,EL,3rd Qualifying Round,Petrolul Ploiesti,Rom,Viktoria Plzen,Cze,1-1,4-1,5-2,no,no
7265,2011/12,EL,4th Qualifying or Play-off Round,AEK Athens,Gre,Dinamo Tbilisi,Geo,1-0,1-1,2-1,no,no
6757,2010/11,CL,Group Stage,Real Madrid,Esp,Ajax,Ned,2-0,4-0,6-0,no,no
6821,2010/11,EL,2nd Qualifying Round,OFK Belgrade,Srb,Torpedo Zhodino,Bls,2-2,1-0,3-2,no,no
6230,2008/09,EL,Group Stage,Hertha BSC,Ger,Benfica,Por,1-1,NaN,1-1,no,no
5292,2005/06,EL,Group Stage,FC Basel,Sui,Tromsø IL,Nor,4-3,NaN,4-3,no,no
4487,2003/04,CL,1st Qualifying Round,Sheriff Tiraspol,Mol,Flora Tallinn,Est,1-0,1-1,2-1,no,no
3273,1998/99,CL,Group Stage,RC Lens,Fra,Panathinaikos,Gre,1-0,0-1,1-1,no,no
2355,1993/94,CW,Round 1,Degerfors IF,Swe,AC Parma,Ita,1-2,0-2,1-4,no,no
1790,1989/90,CW,Round 1,Admira Wacker,Aut,AEL Limassol,Cyp,3-0,0-1,3-1,no,no
1536,1987/88,CL,Final,PSV Eindhoven,Ned,Benfica,Por,0-0,NaN,0-0,no,no
1293,1985/86,CW,Round 1,Rapid Wien,Aut,Tatabánya,Hun,5-0,1-1,6-1,no,no
1332,1985/86,EL,Round 1,Legia Warsaw,Pol,Viking Stavanger,Nor,3-0,1-1,4-1,no,no
142,1976/77,CL,Round 2,Ferencváros,Hun,Dynamo Dresden,GDR,1-0,0-4,1-4,no,no

## Final Notes

> `exta_time` and `penalties` are in the dataframe but not used