In [11]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# UEFA club European Cup Web Scraping

In this notebook, we will develop and review a web scraper to extract all matches played in the major European Club Cup tournments from 1980 onward. The goal is to create a dataset with the following information:

- `season`
- `competition`
- `round`
- `team_a`,
- `country_a`,
- `team_b`,
- `country_b`
- `score_leg1`
- `score_leg2`
- `score_aggregate`
- `extra_time`
- `penalties`

The first step of our analysis will concentrate on single results only, meaning that we will use the information stored in the first nine columns only. The idea, at least as a first insight, is to compare the winning/points ratio of all clubs by nation without giving any weight to the competition, something that can be done in a further step. 

The process to build the webscraper is iterative and is done in collaboration with Claude. The web resources that will be used as main source is well structured and yet contains different spots where the script to scrape the data must be adapted as we collect the data - *learning point*.

## Scraping data from kassiesa.net

- source: [kassiesa.net](https://kassiesa.net/uefa/index.html)

This database contains all match results and calculated coefficients of European Cup football since 1955, covering all rounds including qualifiers. It's one of the most thorough free sources and is well-regarded among football statisticians. It will be used as starting point for collecting the data. A possible exhaustive approach might be:

- Starting with Kassiesa.net as ground truth (it has all three competitions, nationalities, and correct results). Scrapeing the season-by-season match pages (they're structured HTML tables). This will give us ~1980–present across all competitions.
- Supplement with jalapic/champs CSV (free direct download) for Champions League 1980–2017 as a cross-check.
- For the extra-time / penalties distinction, ***Kassiesa.net does not always separate these from 90-min scores***. We may need to cross-reference with EuroCupsHistory (eurocupshistory.com) for knockout rounds specifically.

In [12]:
import subprocess
import sys

# uncomment to run the test

# # Run the uefa_scraper.py script with default arguments
# result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '1981', '--end', '1983', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# # Print the output
# print("STDOUT:")
# print(result.stdout)
# print("STDERR:")
# print(result.stderr)

#### Testing the scripts through the '80

In [13]:
# uncomment to run the test

# # Run the uefa_scraper.py script with default arguments
# result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '1980', '--end', '1990', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# # Print the output
# print("STDOUT:")
# print(result.stdout)
# print("STDERR:")
# print(result.stderr)

#### Testing the scripts through the '90

In [14]:
# uncomment to run the test

# # Run the uefa_scraper.py script with default arguments
# result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '1990', '--end', '2000', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# # Print the output
# print("STDOUT:")
# print(result.stdout)
# print("STDERR:")
# print(result.stderr)

#### Testing the scripts from 2000 to 2010

In [15]:
# uncomment to run the test

# # Run the uefa_scraper.py script with default arguments
# result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '2000', '--end', '2010', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# # Print the output
# print("STDOUT:")
# print(result.stdout)
# print("STDERR:")
# print(result.stderr)

#### Testing the script from 2010 to 2020

In [16]:
# # uncomment to run the test

# # Run the uefa_scraper.py script with default arguments
# result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '2010', '--end', '2020', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# # Print the output
# print("STDOUT:")
# print(result.stdout)
# print("STDERR:")
# print(result.stderr)

#### Testing the script 2020 to 2025

In [17]:
# # uncomment to run the test

# # Run the uefa_scraper.py script with default arguments
# result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '2020', '--end', '2026', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# # Print the output
# print("STDOUT:")
# print(result.stdout)
# print("STDERR:")
# print(result.stderr)

#### Testing the script 1970 to 2026

In [18]:
import subprocess
import sys

# Run the uefa_scraper.py script with default arguments
result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '1970', '--end', '2026', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# Print the output
print("STDOUT:")
print(result.stdout)
print("STDERR:")
print(result.stderr)

STDOUT:
Scraping 57 seasons (1969/70 → 2025/26) …

  1969/70 … 127 matches
  1970/71 … 128 matches
  1971/72 … 127 matches
  1972/73 … 122 matches
  1973/74 … 124 matches
  1974/75 … 120 matches
  1975/76 … 125 matches
  1976/77 … 126 matches
  1977/78 … 125 matches
  1978/79 … 125 matches
  1979/80 … 127 matches
  1980/81 … 128 matches
  1981/82 … 127 matches
  1982/83 … 127 matches
  1983/84 … 125 matches
  1984/85 … 125 matches
  1985/86 … 123 matches
  1986/87 … 123 matches
  1987/88 … 126 matches
  1988/89 … 125 matches
  1989/90 … 127 matches
  1990/91 … 125 matches
  1991/92 … 133 matches
  1992/93 … 139 matches
  1993/94 … 154 matches
  1994/95 … 172 matches
  1995/96 … 181 matches
  1996/97 … 203 matches
  1997/98 … 221 matches
  1998/99 … 226 matches
  1999/00 … 259 matches
  2000/01 … 263 matches
  2001/02 … 263 matches
  2002/03 … 263 matches
  2003/04 … 247 matches
  2004/05 … 311 matches
  2005/06 … 312 matches
  2006/07 … 321 matches
  2007/08 … 327 matches
  2008/09 … 327 matches
  2009/10 … 346 matches
  2010/11 … 348 matches
  2011/12 … 348 matches
  2012/13 … 347 matches
  2013/14 … 347 matches
  2014/15 … 350 matches
  2015/16 … 347 matches
  2016/17 … 344 matches
  2017/18 … 347 matches
  2018/19 … 370 matches
  2019/20 … 370 matches
  2020/21 … 370 matches
  2021/22 … 411 matches
  2022/23 … 405 matches
  2023/24 … 406 matches
  2024/25 … 678 matches
  2025/26 … 659 matches

Total: 13872 matches
Writing → ../data/uefa_results.csv
Done ✓

STDERR:

output:
```
STDOUT:
Scraping 57 seasons (1969/70 → 2025/26) …

  1969/70 … 127 matches
  1970/71 … 128 matches
  1971/72 … 127 matches
  1972/73 … 122 matches
  1973/74 … 124 matches
  1974/75 … 120 matches
  1975/76 … 125 matches
  1976/77 … 126 matches
  1977/78 … 125 matches
  1978/79 … 125 matches
  1979/80 … 127 matches
  1980/81 … 128 matches
  1981/82 … 127 matches
  1982/83 … 127 matches
  1983/84 … 125 matches
  1984/85 … 125 matches
  1985/86 … 123 matches
  1986/87 … 123 matches
  1987/88 … 126 matches
  1988/89 … 125 matches
  1989/90 … 127 matches
  1990/91 … 125 matches
  1991/92 … 133 matches
  1992/93 … 139 matches
  1993/94 … 154 matches
  1994/95 … 172 matches
  1995/96 … 181 matches
  1996/97 … 203 matches
  1997/98 … 221 matches
  1998/99 … 226 matches
  1999/00 … 259 matches
  2000/01 … 263 matches
  2001/02 … 263 matches
  2002/03 … 263 matches
  2003/04 … 247 matches
  2004/05 … 311 matches
  2005/06 … 312 matches
  2006/07 … 321 matches
  2007/08 … 327 matches
  2008/09 … 327 matches
  2009/10 … 346 matches
  2010/11 … 348 matches
  2011/12 … 348 matches
  2012/13 … 347 matches
  2013/14 … 347 matches
  2014/15 … 350 matches
  2015/16 … 347 matches
  2016/17 … 344 matches
  2017/18 … 347 matches
  2018/19 … 370 matches
  2019/20 … 370 matches
  2020/21 … 370 matches
  2021/22 … 411 matches
  2022/23 … 405 matches
  2023/24 … 406 matches
  2024/25 … 678 matches
  2025/26 … 659 matches

Total: 13872 matches
Writing → ../data/uefa_results.csv
Done ✓

STDERR:
```

In [19]:
raw_data = pd.read_csv('../data/uefa_results.csv')
raw_data.head()

,season,competition,round,team_a,country_a,team_b,country_b,score_leg1,score_leg2,score_aggregate,extra_time,penalties
0,1969/70,CL,Qualifying Round,TPS Turku,Fin,KB København,Den,0-1,0-4,0-5,no,no
1,1969/70,CL,Round 1,Leeds United,Eng,Lyn Oslo,Nor,10-0,6-0,16-0,no,no
2,1969/70,CL,Round 1,CSKA Sofia,Bul,Ferencváros,Hun,2-1,1-4,3-5,no,no
3,1969/70,CL,Round 1,Standard Liège,Bel,17 Nëntori Tirana,Alb,3-0,1-1,4-1,no,no
4,1969/70,CL,Round 1,Real Madrid,Esp,Olympiakos Nicosia,Cyp,8-0,6-1,14-1,no,no

In [20]:
raw_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13872 entries, 0 to 13871
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   season           13872 non-null  str
 1   competition      13872 non-null  str
 2   round            13872 non-null  str
 3   team_a           13872 non-null  str
 4   country_a        13872 non-null  str
 5   team_b           13872 non-null  str
 6   country_b        13872 non-null  str
 7   score_leg1       13872 non-null  str
 8   score_leg2       12303 non-null  str
 9   score_aggregate  13872 non-null  str
 10  extra_time       13872 non-null  str
 11  penalties        13872 non-null  str
dtypes: str(12)
memory usage: 1.3 MB

In [21]:
raw_data.head()

,season,competition,round,team_a,country_a,team_b,country_b,score_leg1,score_leg2,score_aggregate,extra_time,penalties
0,1969/70,CL,Qualifying Round,TPS Turku,Fin,KB København,Den,0-1,0-4,0-5,no,no
1,1969/70,CL,Round 1,Leeds United,Eng,Lyn Oslo,Nor,10-0,6-0,16-0,no,no
2,1969/70,CL,Round 1,CSKA Sofia,Bul,Ferencváros,Hun,2-1,1-4,3-5,no,no
3,1969/70,CL,Round 1,Standard Liège,Bel,17 Nëntori Tirana,Alb,3-0,1-1,4-1,no,no
4,1969/70,CL,Round 1,Real Madrid,Esp,Olympiakos Nicosia,Cyp,8-0,6-1,14-1,no,no

In [22]:
raw_data[raw_data['round'] ==  'Final'][:10]

,season,competition,round,team_a,country_a,team_b,country_b,score_leg1,score_leg2,score_aggregate,extra_time,penalties
31,1969/70,CL,Final,Feyenoord,Ned,Celtic,Sco,2-1,NaN,2-1,no,no
63,1969/70,CW,Final,Manchester City,Eng,Górnik Zabrze,Pol,2-1,NaN,2-1,no,no
126,1969/70,INTER-CITIES FAIRS CUP,Final,Anderlecht,Bel,Arsenal,Eng,3-1,0-3,3-4,no,no
158,1970/71,CL,Final,Ajax,Ned,Panathinaikos,Gre,2-0,NaN,2-0,no,no
191,1970/71,CW,Final,Chelsea,Eng,Real Madrid,Esp,1-1,NaN,1-1,no,no
254,1970/71,INTER-CITIES FAIRS CUP,Final,Juventus,Ita,Leeds United,Eng,2-2,1-1,3-3,no,no
286,1971/72,CL,Final,Ajax,Ned,Internazionale,Ita,2-0,NaN,2-0,no,no
319,1971/72,CW,Final,Glasgow Rangers,Sco,Dinamo Moscow,URS,3-2,NaN,3-2,no,no
381,1971/72,EL,Final,Wolverhampton Wanderers,Eng,Tottenham Hotspur,Eng,1-2,1-1,2-3,no,no
410,1972/73,CL,Final,Ajax,Ned,Juventus,Ita,1-0,NaN,1-0,no,no

The scraper addresses properly the fact that some finals were played within a single match.

## Sample checking

The dataset contains 12747 entries and checking all of them would be an extensive taks. One feasible strategy is to sample $n$ entries and double veryfing the reported information. The size of the sample may depend on the size of the dataset and the cost to verify the information (the cost involve the time and resources you need to verify).

In [23]:
raw_data.sample(20, random_state=1).sort_values('season', ascending = False)

,season,competition,round,team_a,country_a,team_b,country_b,score_leg1,score_leg2,score_aggregate,extra_time,penalties
12593,2024/25,CL,League Stage,Red Star Belgrade,Srb,Benfica,Por,1-2,NaN,1-2,no,no
12862,2024/25,EL,League Stage,Dynamo Kyiv,Ukr,Viktoria Plzen,Cze,1-2,NaN,1-2,no,no
11876,2022/23,EL,Group Stage,Real Sociedad,Esp,Omonia Nicosia,Cyp,2-1,2-0,4-1,no,no
11408,2021/22,CL,Group Stage,Chelsea,Eng,Malmö FF,Swe,4-0,1-0,5-0,no,no
11320,2021/22,CL,1st Qualifying Round,Connah's Quay,Wal,Alashkert FC,Arm,2-2,0-1,2-3,no,no
9068,2014/15,EL,Group Stage,Club Brugge,Bel,Torino,Ita,0-0,0-0,0-0,no,no
9153,2014/15,EL,Round 3,VfL Wolfsburg,Ger,Internazionale,Ita,3-1,2-1,5-2,no,no
8887,2014/15,CL,Group Stage,CSKA Moscow,Rus,Bayern München,Ger,0-1,0-3,0-4,no,no
8347,2012/13,EL,4th Qualifying or Play-off Round,Slask Wroclaw,Pol,Hannover 96,Ger,3-5,1-5,4-10,no,no
7245,2009/10,EL,2nd Qualifying Round,Sliema Wanderers,Mlt,Maccabi Netanya,Isr,0-0,0-3,0-3,no,no
7036,2008/09,EL,Group Stage,Club Brugge,Bel,FC København,Den,0-1,NaN,0-1,no,no
4900,2001/02,EL,Round 1,Girondins Bordeaux,Fra,DVSC Debrecen,Hun,5-1,1-3,6-4,no,no
4643,2000/01,EL,Round 1,Partizan Belgrade,Srb,FC Porto,Por,1-1,0-1,1-2,no,no
3589,1996/97,CW,Qualifying Round,Glentoran,Nir,Sparta Praha,Cze,1-2,0-8,1-10,no,no
3660,1996/97,EL,2nd Qualifying Round,Dinamo Moscow,Rus,Jazz Pori,Fin,1-1,3-1,4-2,no,no
3564,1996/97,CL,Group Stage,FC Porto,Por,IFK Göteborg,Swe,2-1,2-0,4-1,no,no
3570,1996/97,CL,Quarter Finals,Rosenborg BK,Nor,Juventus,Ita,1-1,0-2,1-3,no,no
3086,1993/94,CW,Qualifying Round,1.FC Kosice,Svk,Zalgiris Vilnius,Lit,2-1,1-0,3-1,no,no
943,1976/77,EL,Round 1,CF Os Belenenses,Por,FC Barcelona,Esp,2-2,2-3,4-5,no,no
663,1974/75,CW,Round 1,Gwardia Warsaw,Pol,Bologna,Ita,2-1,1-2,3-3,no,no

## Final Notes

> `exta_time` and `penalties` are in the dataframe but not used